version: '3.8'

services:
  postgres_db:
    # Dùng bản alpine cho nhẹ máy, khởi động cực nhanh
    image: postgres:15-alpine
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_cua_ban
    ports:
      # Ánh xạ cổng: [Cổng máy tính] : [Cổng bên trong Docker]
      - "5432:5432"
    volumes:
      # Ánh xạ thư mục để dữ liệu không bị mất khi tắt Docker
      - pgdata:/var/lib/postgresql/data

volumes:
  # Khai báo volume lưu trữ liên tục (Persistent Storage)
  pgdata: