ALTER TABLE users ADD COLUMN daily_notif_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN ai_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN billing_cycle_day INTEGER NOT NULL DEFAULT 5;
